name: SAGE-CartNet
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pyg=2.5.2
  - pytorch-scatter=2.1.1
  - numpy=1.24.*
  - scipy=1.13.*
  - scikit-learn=1.5.*
  - matplotlib=3.9.*
  - tqdm
  - wandb
  - yacs
  - pyyaml
  - tabulate
  - psutil
  - jarvis-tools=2024.8.30
